### PR TITLE
NodeBoxEditor 0.9.0

### PR DESCRIPTION
**Pull request by rubenwardy**
### New Features

* More flexible media finding (finding media folder on startup)
* Viewport zooming.
* Smooth rotation in perspective viewport.
* Fractional input to nodebox properties.
* Add dynamic snapping resolution.
* Add snap resolution to node properties.
* Add links to help menu (help, forum, bug tracker).

### Bug Fixes
* Fix texture leaks:
    * NB resize, delete.
    * Texture editor and dialog (@asl97)
* Only rebuild nodebox meshes if they have changed.
* Correct front and back viewports being the wrong way around. (front was back, back was front)
* Hide drag handles when they go outside of a viewport.
* Fix pixel snapping during shift move.
* Fix DIR_DELIM warning.
* Change working directory when running Minetest to stop problems in non-portable builds.
* Add media/flip* to make install

### Misc / Maintenance

* Add debug features (texture/face count)
* Prepend enum type names with E.
* Collect project related code into project/.
* Better function names in NodeBox class.
* Add more possible minetest dir locations

### CODE REVIEW

**Comment by SmallJoker** [comment]
\o/ Finally!

**Comment by rubenwardy** [comment]
The release process has begun, going to leave the re-adding of the snippet tool to 0.8.3.

**Comment by rubenwardy** [comment]
Just need to make and test a windows build now. Especially the new website openers in the help menu.

**Comment by SmallJoker** [comment]
..\source\src\util\filesys.cpp(46): fatal error C1083: File (Include) can not be opened: "linux.h": No such file or directory

**Comment by rubenwardy** [comment]
I may have accidentally ran s/windows/linux/g, as it's the example given by this site: http://vasir.net/blog/ubuntu/replace_string_in_multiple_files

**Comment by rubenwardy** [comment]
linux.h doesn't even exist.

**Comment by rubenwardy** [comment]
Yes, my instinct was right: https://github.com/rubenwardy/NodeBoxEditor/commit/e8d9a23d1ec4e7cbcb57228a5902c28388ec2322#diff-0f4445909e5f57fd9359090fd0d033ccL46

Also see the comment change in the file below

> Use windows separator on windows and unix separator on unix.

to

> Use linux separator on linux and unix separator on unix.

**Pull request merged**
