### PR TITLE
Fix memory leak

### LINKED ISSUE #71: Memory leak
everything was fine until i imported a image and added it into the node
____
more info from alleyoop, frontend of valgrind, killed quite early so it was just a little bit over 300mb

```
==30484== 304,576,976 bytes in 335 blocks are still reachable in loss record 1,076 of 1,076
==30484==    at 0x04c2a77c: operator
==30484==    by 0x0515c562: irr::video::CImage::initData() (in /usr/lib64/libIrrlicht.so.1.8.1)
==30484==    by 0x0515c625: irr::video::CImage::CImage(irr::video::ECOLOR_FORMAT, irr::core::dimension2d<unsigned int> const&) (in /usr/lib64/libIrrlicht.so.1.8.1)
==30484==    by 0x0512d54e: irr::video::CNullDriver::createImage(irr::video::ECOLOR_FORMAT, irr::core::dimension2d<unsigned int> const&) (in /usr/lib64/libIrrlicht.so.1.8.1)
==30484==
```
____
i notice there is a high cpu load when the texture menu is open once a image is loaded and selected (apply), might be link to the memory leak cause it only grow when the texture menu is open

### PR DESCRIPTION
**Pull request by asl97**
fixes #71

### CODE REVIEW

**Comment by rubenwardy** [comment]
Wow...

I didn't really understand textures when I was creating those parts. I've fixed a few other texture leaks on the dev branch: 0f152ab919461c030f59b8ce3da9f8da744a02c8 and 866ca6b16aea8198a4e444056ff54e979fc7e83b

I'm going to have to start work on the 0.8.2 part soon to fix these. Thank you for your help.

**Comment by rubenwardy** [comment]
49daaedad3886e0d1edbc7f14f5f52a013f30b9f

**Comment by rubenwardy** [comment]
What's the difference between `driver->removeTexture(texture)` and `texture->drop()`?

Is the latter a reference counter, so takes 1 from the `count` and if `count <= 0` it does `removeTexture()`

**Comment by asl97** [comment]
@rubenwardy to be honest, i don't really know, i saw a post on a forum somewhere that remove the texture after it was done drawing it.

since it is only use on one place, it should be fine to just remove it.

**Pull request closed without merging**
